config/routes.rb
Rails.application.routes.draw do
  root 'statics#top'
  get :dashboard, to: 'teams#dashboard'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resource :user
  
  resources :teams do
    resources :assigns, only: %w(create destroy)
    resources :agendas, shallow: true do
      resources :articles do
        resources :comments
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save!
        format.js { render :index }
      else
        format.html { redirect_to article_path(@article), notice: I18n.t('views.messages.failed_to_post') }
      end
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @article = @comment.article
    redirect_to article_path(@article) if @comment.update(comment_params)
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.js { render :index }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:article_id, :content, :article_id)
  end
end

app/views/comments/_form.html.erb
<%= form_with(model: [article, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content, class: "comment_input" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<!-- この記述がarticleのshow画面に表示されるコメント入力欄になります -->

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <p><%= comment.content %></p>
        <% if comment.user.try(:email) %>
          <%= I18n.t('views.messages.author') %>：<%= comment.user.email %><br>
        <% else %>
          Not User Data<br>
        <% end %>

        <% if comment.user == current_user || current_user.id == comment.article.team.owner_id %>
          <p>
            <%= link_to I18n.t('views.messages.delete_comment'), comment_path(comment), method: :delete, remote: true %>
            / <%= link_to I18n.t('views.messages.edit_comment'), edit_comment_path(comment) %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<br><br><br>
<%= form_with(model: @comment, local: true) do |form| %>
  <div class="field">
    <%= form.text_area :content, class: "comment_input" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.article.comments, article: @comment.article }) %>")
$("textarea").val('')