config/routes.rb
Rails.application.routes.draw do
  root 'statics#top'
  get :dashboard, to: 'teams#dashboard'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resource :user
  
  resources :teams do
    resources :assigns, only: %w(create destroy)
    resources :agendas, shallow: true do
      resources :articles do
        resources :comments
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 1, maximum: 100 }
  validates :content, presence: true, length: { minimum: 1, maximum: 1000 }
  belongs_to :user
  belongs_to :team
  belongs_to :agenda
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @agendas = Agenda.all
    @articles = Article.all
  end

  def show
    @comments = @article.comments
    @comment = @article.comments.build
    @working_team = @article.team
    change_keep_team(current_user, @working_team)
  end

  def new
    @agenda = Agenda.find(params[:agenda_id])
    @team = @agenda.team
    @article = @agenda.articles.build
  end

  def edit
    change_keep_team(current_user, @article.team)
  end

  def create
    agenda = Agenda.find(params[:agenda_id])
    article = agenda.articles.build(article_params)
    article.user = current_user
    article.team_id = agenda.team_id
    if article.save
      redirect_to article_url(article), notice: I18n.t('views.messages.create_article')
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: I18n.t('views.messages.update_article')
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to dashboard_url
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.fetch(:article, {}).permit %i[title content image image_cache]
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, url: select_posting_article_path(article), local: true) do |form| %>
  <% if article.errors.any? %>
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h5>
        <i class="icon fa fa-ban"></i>
        <%= pluralize(article.errors.count, "error") %> prohibited this team from being saved:
      </h5>
      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: I18n.t('views.messages.input_title'), class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, placeholder: I18n.t('views.messages.input_content'), class: 'form-control', rows: 10 %>
  </div>

  <div class="form-group">
    <%= form.label :image %><br>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="form-group">
    <%= form.submit I18n.t('views.button.submit'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="row mt-3">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= I18n.t('views.messages.edit_article') %>
        </h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <%= render 'form', article: @article %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
  <!-- ./col -->
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_agenda_article_path(@agenda) %>

app/views/articles/new.html.erb
<div class="row mt-3">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= I18n.t('views.messages.create_article') %>
        </h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <%= render 'form', article: @article %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
  <!-- ./col -->
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= @article.title %>
        </h3>
        <%= @article.user.email %>
        <%= l(@article.created_at, format: :long) %>
        <%= link_to I18n.t('views.button.edit'), edit_article_path(@article) %>
        <%= link_to I18n.t('views.button.delete'), article_path(@article), method: :delete %>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <%= markdown(@article.content).html_safe %>
        <%= image_tag @article.image_url if @article.image_url %>
      </div>

      <p><%= I18n.t('views.messages.comment_list') %></p>
      <div id="comments_area" class="comments_area_form">
        <!-- 投稿されたコメント一覧をarticleの詳細ページに表示するためのrender -->
        <%= render partial: 'comments/index', locals: { comments: @comments, article: @article } %>
      </div>

      <p><%= I18n.t('views.messages.post_comment') %></p>
      <!-- コメント入力欄をarticleの詳細ページに表示するためのrender -->
      <%= render partial: 'comments/form', locals: { comment: @comment, article: @article } %>

      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
  <!-- ./col -->
</div>