config/routes.rb
Rails.application.routes.draw do
  root 'statics#top'
  get :dashboard, to: 'teams#dashboard'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resource :user
  
  resources :teams do
    resources :assigns, only: %w(create destroy)
    resources :agendas, shallow: true do
      resources :articles do
        resources :comments
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/layout/_footer.html.erb
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
    Anything you want
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2016-2018 <a href="https://diveintocode.jp">DIVEINTOPOST</a>.</strong> All rights reserved.
</footer>

app/views/shared/layout/_header.html.erb
<nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
        <i class="fa fa-th-large"></i>
      </a>
    </li>
  </ul>
</nav>

app/views/shared/layout/_menu.html.erb
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
  <div class="p-3">
    <% if user_signed_in? %>
      <h5>Menu</h5>
      <p><%= link_to I18n.t('views.messages.my_page'), user_path %></p>
      <p><%= link_to I18n.t('views.messages.team_build'), new_team_path %></p>

      <h5><%= I18n.t('views.messages.select_team') %></h5>
      <% (current_user.teams.blank? ? Team.where(id: 1) : current_user.teams).each do |team| %>
        <%= link_to team_path(team) do %>
          <p>
            <%= image_tag default_img(team.icon_url), size: '30x30' %>&nbsp;
            <%= team.name %>
          </p>
        <% end %>
      <% end %>

      <p>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-block' %>
      </p>
    <% end %>
  </div>
</aside>

app/views/shared/layout/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <%= link_to dashboard_url, class: 'brand-link' do %>
    <span class="brand-text font-weight-light">DIVE INTO POST</span>
  <% end %>

  <!-- Sidebar -->
  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3">
      <div class="info">
        <h3 style="color: white;"><%= @working_team.name.truncate(15) %></h3>
      </div>
    </div>

    <div class="user-panel mt-3 pb-3 mb-3">
      <div class="info">
        <a href="#" class="d-block mb-1"><%= I18n.t('views.messages.create_agenda') %></a>
        <%= form_with model: :agenda, scope: :post, url: team_agendas_path(@working_team), local: true do |form| %>
          <div class="input-group input-group-sm">
            <%= text_field_tag :title, '', { class: 'form-control', placeholder: I18n.t('views.messages.input_agenda_title') } %>
            <span class="input-group-append">
              <button type="submit" class="btn btn-info btn-flat"><%= I18n.t('views.button.create') %></button>
            </span>
          </div>
        <% end %>
      </div>
    </div>
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <% @working_team.agendas.each do |agenda| %>
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="form inline">
              <i class="fa fa-circle-o nav-icon"></i>

                <%= agenda.title %><%= link_to 'Delete', agenda, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-danger" %> 
                <i class="right fa fa-angle-left"></i>
                    
    
            </a>

            <ul class="nav nav-treeview" style="display: block;">
              <% agenda.articles.each do |article| %>
                <li class="nav-item">
                  <%= link_to article_path(article), class: 'nav-link' do %>
                    <p><%= article.title %></p>
                  <% end %>
                </li>
              <% end %>
              <li class="nav-item">
                <%= link_to new_agenda_article_path(agenda), class: 'nav-link' do %>
                  <p>+ <%= I18n.t('views.messages.create_article') %></p>
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>