config/routes.rb
Rails.application.routes.draw do
  root 'statics#top'
  get :dashboard, to: 'teams#dashboard'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resource :user
  
  resources :teams do
    resources :assigns, only: %w(create destroy)
    resources :agendas, shallow: true do
      resources :articles do
        resources :comments
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/agenda.rb
class Agenda < ApplicationRecord
  belongs_to :team
  belongs_to :user
  has_many :articles, dependent: :destroy
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :set_agenda, only: %i[show edit update destroy]

  def index
    @agendas = Agenda.all
  end

  def new
    @team = Team.friendly.find(params[:team_id])
    @agenda = Agenda.new
  end

  def create
    @agenda = current_user.agendas.build(title: params[:title])
    @agenda.team = Team.friendly.find(params[:team_id])
    current_user.keep_team_id = @agenda.team.id
    if current_user.save && @agenda.save
      redirect_to dashboard_url, notice: I18n.t('views.messages.create_agenda') 
    else
      render :new
    end
  end

  def destroy
   if current_user.id==@agenda.user_id
      @agenda.destroy
      @agenda.team.assigns.each do |assign|  
        ContactMailer.contact_mail(assign.user.email,@agenda).deliver
      end
      #ContactMailer.contact_mail(@agenda).deliver
      redirect_to dashboard_url, notice: "agenda deleted "
   else
     redirect_to dashboard_url, notice: "you can't delete other owner's agenda"
   end
 end

  private

  def set_agenda
    @agenda = Agenda.find(params[:id])
  end

  def agenda_params
    params.fetch(:agenda, {}).permit %i[title description]
  end
end

app/helpers/agendas_helper.rb
module AgendasHelper
  def choose_new_or_edit
    if action_name == 'new'
      team_agendas_path
    elsif action_name == 'edit'
      agenda_path
    end
  end
end

app/views/agendas/_form.html.erb
<%= form_with(model: @agenda, local: true, url: choose_new_or_edit) do |form| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% @agenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agendas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agendas.includes(:articles).each do |agenda| %>
      <table>
        <tr>Agenda title:<%= agenda.title %></tr>
        <br />
        <% agenda.articles.each do |article| %>
          <li>Article title:<%= article.title %></li>
        <% end %>
      </table>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agenda', new_team_agenda_path %>

app/views/agendas/new.html.erb
<h1>New Agenda</h1>
<%= form_with(model: [@team, @agenda], local: true) do |form| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% @agenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', team_agendas_path %>